# Checkov GitHub Action
# This workflow runs Checkov to scan for infrastructure as code (IaC) security issues.
# It runs on every push and pull request to main branches.

name: Checkov

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

permissions:
  contents: read

jobs:
  checkov:
    name: Run Checkov
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@v12
        with:
          directory: .
          quiet: true
          soft_fail: false
